// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// OnlineSince provides a mock function with no fields
func (_m *Service) OnlineSince() (time.Duration, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for OnlineSince")
	}

	var r0 time.Duration
	var r1 error
	if rf, ok := ret.Get(0).(func() (time.Duration, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_OnlineSince_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnlineSince'
type Service_OnlineSince_Call struct {
	*mock.Call
}

// OnlineSince is a helper method to define mock.On call
func (_e *Service_Expecter) OnlineSince() *Service_OnlineSince_Call {
	return &Service_OnlineSince_Call{Call: _e.mock.On("OnlineSince")}
}

func (_c *Service_OnlineSince_Call) Run(run func()) *Service_OnlineSince_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_OnlineSince_Call) Return(_a0 time.Duration, _a1 error) *Service_OnlineSince_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_OnlineSince_Call) RunAndReturn(run func() (time.Duration, error)) *Service_OnlineSince_Call {
	_c.Call.Return(run)
	return _c
}

// SetOnlineSince provides a mock function with given fields: _a0
func (_m *Service) SetOnlineSince(_a0 time.Time) {
	_m.Called(_a0)
}

// Service_SetOnlineSince_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOnlineSince'
type Service_SetOnlineSince_Call struct {
	*mock.Call
}

// SetOnlineSince is a helper method to define mock.On call
//   - _a0 time.Time
func (_e *Service_Expecter) SetOnlineSince(_a0 interface{}) *Service_SetOnlineSince_Call {
	return &Service_SetOnlineSince_Call{Call: _e.mock.On("SetOnlineSince", _a0)}
}

func (_c *Service_SetOnlineSince_Call) Run(run func(_a0 time.Time)) *Service_SetOnlineSince_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Time))
	})
	return _c
}

func (_c *Service_SetOnlineSince_Call) Return() *Service_SetOnlineSince_Call {
	_c.Call.Return()
	return _c
}

func (_c *Service_SetOnlineSince_Call) RunAndReturn(run func(time.Time)) *Service_SetOnlineSince_Call {
	_c.Run(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
